### ISSUE TITLE
Passive voice results

### ISSUE THREAD

**Issue by dereckmartin** [markfullmer/grammark#5]
After running text through the new grammark, and correcting passive errors, the vintage grammark catches additional passive errors not caught by the new grammark.  Is this an error, or is this to be expected?  This question is an example of the issue.  You can copy and paste this into both and see that the vintage version catches more.

**Comment by markfullmer** [comment]
Hi dereckmartin,
In the new Grammark, the "...be [past tense verb]" is not included in the list of things to mark as passive constructions (whereas it will catch "was [past tense verb]" (http://note.io/200KrqV). I think I made this change because I thought "be [past tense verb]" returned too many false positives, but I currently cannot think of such instances. With your approval, I can add this functionality back to the new version of Grammark.

**Comment by dereckmartin** [comment]
I am okay with adding it back.

**Comment by markfullmer** [comment]
This issue has been resolved. "be" type passive voice will now be identified.
